# Generated by Django 6.0.4 on 2026-04-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='kilometrage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reparation',
            name='niveau_carburant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.CharField(choices=[('PROFORMA', 'Proforma'), ('DEFINITIVE', 'Définitive')], default='PROFORMA', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('reparation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='api.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='LignePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='api.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='api.reparation')),
            ],
        ),
    ]
