# Generated by Django 6.0.4 on 2026-04-29 08:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reparation_kilometrage_reparation_niveau_carburant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ESPECE', 'Espèce'), ('MOMOPAY', 'MomoPay'), ('VIREMENT', 'Virement Bancaire'), ('CHEQUE', 'Chèque'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut_paiement',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiel'), ('SOLDE', 'Soldé')], default='NON_PAYE', max_length=20),
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateField(default=django.db.models.functions.datetime.Now())),
                ('type_mouvement', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('categorie', models.CharField(choices=[('ACHAT_PIECES', 'Achats pièces'), ('SALAIRES', 'Salaires'), ('LOYER', 'Loyer / Charges'), ('CARBURATION', 'Carburation'), ('RECETTE_CLIENT', 'Règlement Client'), ('AUTRE_RECETTE', 'Autre Recette'), ('AUTRE_DEPENSE', 'Autre Dépense')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='api.facture')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
