# Generated by Django 6.0.4 on 2026-05-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_facture_mode_paiement_facture_montant_paye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('FACTURE', 'Facturé')], default='BROUILLON', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.reparation')),
            ],
        ),
    ]
