# Generated by Django 6.0.4 on 2026-05-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepiece',
            name='article_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stock'),
        ),
    ]
