# Generated by Django 6.0.4 on 2026-05-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lignepiece_article_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePredictive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('VIDANGE', 'Vidange'), ('REVISION', 'Révision Générale'), ('COURROIE', 'Courroie de Distribution'), ('PNEUS', 'Changement Pneus')], max_length=20)),
                ('date_derniere_prestation', models.DateField(auto_now_add=True)),
                ('km_derniere_prestation', models.IntegerField()),
                ('date_prochaine_prevue', models.DateField(blank=True, null=True)),
                ('km_prochain_prevu', models.IntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_futures', to='api.vehicule')),
            ],
        ),
    ]
