# Generated by Django 6.0.4 on 2026-05-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appointment_notificationclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nom_client_public',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telephone_client_public',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.client'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='type',
            field=models.CharField(choices=[('REPARATION_TERMINEE', 'Réparation terminée'), ('RAPPEL_MAINTENANCE', 'Rappel maintenance'), ('RDV_CONFIRME', 'RDV Confirmé')], max_length=30),
        ),
        migrations.DeleteModel(
            name='VisiteTechnique',
        ),
    ]
