# Generated by Django 6.0.4 on 2026-05-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment_nom_client_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationclient',
            name='type',
            field=models.CharField(choices=[('REPARATION_TERMINEE', 'Réparation terminée'), ('RAPPEL_MAINTENANCE', 'Rappel maintenance'), ('RDV_CONFIRME', 'RDV Confirmé'), ('FACTURE_ENVOYEE', 'Facture envoyée'), ('DEVIS_ENVOYE', 'Devis envoyé')], max_length=30),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=5)),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affiche_public', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='api.client')),
                ('reparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='api.reparation')),
            ],
        ),
    ]
