# Generated by Django 6.0.4 on 2026-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_client_photo_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOUVEAU_RDV', 'Nouveau Rendez-vous'), ('NOUVEL_AVIS', 'Nouvel Avis Client'), ('STOCK_BAS', 'Alerte Stock Bas'), ('PAIEMENT_RECU', 'Paiement Reçu')], max_length=30)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
