# Generated by Django 6.0.4 on 2026-05-22 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='api.reparation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reparation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='api.reparation'),
        ),
        migrations.AlterField(
            model_name='lignepiece',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='api.reparation'),
        ),
        migrations.AlterField(
            model_name='lignetravail',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travaux', to='api.reparation'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='date_mouvement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparations', to='api.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='api.client'),
        ),
    ]
