# Generated by Django 6.0.4 on 2026-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_client_contact_alter_devis_reparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de chèque'),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference_virement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence virement'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='numero_or',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='N° Ordre de Réparation'),
        ),
    ]
