# Generated by Django 6.0.4 on 2026-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_stock_quantite_alter_stock_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='emecef_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='emecef_counters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='emecef_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='emecef_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='emecef_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_normalised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ESPECE', 'Espèce'), ('MOMOPAY', 'MomoPay'), ('VIREMENT', 'Virement Bancaire'), ('CHEQUE', 'Chèque'), ('KKIAPAY', 'Kkiapay'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
    ]
