# Generated by Django 6.0.4 on 2026-06-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_facture_emecef_code_facture_emecef_counters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ifu',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Numéro IFU'),
        ),
        migrations.AddField(
            model_name='facture',
            name='demande_normalisation',
            field=models.BooleanField(default=False, verbose_name='Facture normalisée demandée'),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='type',
            field=models.CharField(choices=[('REPARATION_TERMINEE', 'Réparation terminée'), ('RAPPEL_MAINTENANCE', 'Rappel maintenance'), ('RDV_CONFIRME', 'RDV Confirmé'), ('FACTURE_ENVOYEE', 'Facture envoyée'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('PAIEMENT_CONFIRME', 'Paiement confirmé'), ('MODIFICATION_ACCEPTEE', 'Modification prise en compte')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='type',
            field=models.CharField(choices=[('NOUVEAU_RDV', 'Nouveau Rendez-vous'), ('NOUVEL_AVIS', 'Nouvel Avis Client'), ('STOCK_BAS', 'Alerte Stock Bas'), ('PAIEMENT_RECU', 'Paiement Reçu'), ('DEMANDE_MODIFICATION_PROFORMA', 'Demande de modification proforma')], max_length=30),
        ),
        migrations.CreateModel(
            name='LogNormalisationEmecef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('SIMULATION', 'Simulation (dev)')], max_length=15)),
                ('payload_envoye', models.JSONField(blank=True, null=True, verbose_name='Payload envoyé à la DGI')),
                ('reponse_recue', models.JSONField(blank=True, null=True, verbose_name='Réponse reçue de la DGI')),
                ('code_http', models.IntegerField(blank=True, null=True, verbose_name='Code HTTP de la réponse')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Détail de l'erreur")),
                ('uid_emecef', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID e-MECeF retourné')),
                ('date_tentative', models.DateTimeField(auto_now_add=True, verbose_name='Date de la tentative')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_emecef', to='api.facture')),
            ],
            options={
                'verbose_name': 'Log Normalisation e-MECeF',
                'verbose_name_plural': 'Logs Normalisation e-MECeF',
                'ordering': ['-date_tentative'],
            },
        ),
    ]
