# Generated by Django 6.0.4 on 2026-06-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ifu_demande_normalisation_log_emecef'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='api.reparation')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
