# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_etapereparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepiece',
            name='origine_piece',
            field=models.CharField(
                choices=[
                    ('STOCK', 'Stock garage'),
                    ('COMMANDE_EXTERNE', 'Commande extérieure'),
                    ('FOURNIE_CLIENT', 'Fournie par le client'),
                ],
                default='STOCK',
                max_length=30,
            ),
        ),
    ]
