# Generated by Django 6.0.4 on 2026-07-09 10:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lignepiece_origine_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_garage', models.CharField(default='Luxury Elegance Garage', max_length=200)),
                ('ifu', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFU')),
                ('rccm', models.CharField(blank=True, max_length=50, null=True, verbose_name='RCCM')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='garage/')),
                ('solde_ouverture_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='TVA par défaut (%)')),
                ('seuil_alerte_stock_defaut', models.IntegerField(default=10, verbose_name='Seuil alerte stock')),
            ],
            options={
                'verbose_name': 'Paramètres du Garage',
                'verbose_name_plural': 'Paramètres du Garage',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=api.models.default_dashboard_preferences, help_text='Liste des widgets activés pour le dashboard du Directeur.', verbose_name='Widgets du tableau de bord'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
